# 記述方法
# pathに対して検知する対象のパスを指定してください。
# 末尾が/で終わっているpathはディレクトリとして認識して、path配下に差分がある場合にchecklistsの内容を追記します。
# 末尾が/以外のものはpath指定と認識し完全一致で差分が発生した場合にchecklistsの内容を追記します。
# checklistsはそれぞれ改行され、マークダウン記法が使用できます。
setting: 
  - path: 'test.py'
    checklists: 
      - '- [ ] test'
      - "    - [ ] test"
  - path: 'test'
    checklists:
      - "- [ ] Lambda→AWS Batchへの切替の場合、アーキテクチャ変更による影響確認（タイムアウト時間など）"
      - "    - [ ] "
  - path: 'api/' # TODO
    riskeyPatterns:
      - 'Key\\(".*s"\\)\\.eq\\(\\[\\]\\)'
      - 'Key\\(".*s"\\)\\.eq\\(None\\)'
      - 'Attr\\(".*s"\\)\\.not_exists\\(\\)'
      - 'Attr\\(".*s"\\)\\.eq\\(\\[\\]\\)'
      - 'Attr\\(".*s"\\)\\.eq\\(None\\)'
    checklists: 
      - "- [ ] 配列の項目で絞り込みを実施している場合、空配列またはNoneの場合でも想定通りの挙動となるか確認"
      - "    - [ ] hogehoge"