# 記述方法
# pathに対して検知する対象のパスを指定してください。
# 末尾が/で終わっているpathはディレクトリとして認識して、path配下に差分がある場合にchecklistsの内容を追記します。
# 末尾が/以外のものはpath指定と認識し完全一致で差分が発生した場合にchecklistsの内容を追記します。
# checklistsはそれぞれ改行され、マークダウン記法が使用できます。
setting: 
  - path: 'test.py'
    checklists: 
      - '- [ ] RDS桁制限と管理画面との入力制限との整合性が取れているか'
      - "    - [ ] "
  - path: 'test'
    checklists:
      - "- [ ] Lambda→AWS Batchへの切替の場合、アーキテクチャ変更による影響確認（タイムアウト時間など）"
      - "    - [ ] "
