repos:
  - repo: https://github.com/FMsAkamineTaito/pre-commit-test
    rev: 6fb21a04028170270d6604eec8b68c60539180f1
    hooks:
      - id: pr-status-check
        name: pre-commit-test
        stages: [pre-merge-commit]
        always_run: true
        verbose: true
        log_file: /Users/akaminetaito/Desktop/log.txt