repos:
  - repo: https://github.com/FMsAkamineTaito/pre-commit-test
    rev: 04e60dcf80c2f21803bfc921504194458e2f22e1
    hooks:
      - id: pr-status-check
        name: pre-commit-test
        stages: [post-checkout]
        always_run: true
        verbose: true
        log_file: /Users/akaminetaito/Desktop/log.txt
  - repo: local
    hooks:
      - id: handle-merge-failure
        name: handle-merge-failure
        entry: |
          bash -c '
            echo "handle-merge-failure"
            echo "handle-merge-failure" > "/Users/akaminetaito/Desktop/log.txt";
            echo $(ls .git/) > "/Users/akaminetaito/Desktop/log.txt";
            ls .git/
            sleep 5
          '
        language: system