repos:
  - repo: https://github.com/FULL-MARKS-INC/code-checker
    rev: 9178df1269261f565d13ea9b856d8a3432d434ec
    hooks:
      - id: pr-status-checker
        pass_filenames: false
        verbose: true
        stages: [prepare-commit-msg]