repos:
  - repo: https://github.com/FMsAkamineTaito/pre-commit-test
    rev: a41a0c2390515a857bfa52a124ab97ae7b2c4d75
    hooks:
      - id: pr-status-check
        name: pre-commit-test
        stages: [prepare-commit-msg]
        verbose: true
        log_file: /Users/akaminetaito/Desktop/log.txt
