repos:
  - repo: https://github.com/FULL-MARKS-INC/code-checker
    rev: 61e9fbe1502ec97444a47d7ca600e42cd5a0e499
    hooks:
      - id: pr-status-checker
        pass_filenames: false
        verbose: true
        stages: [prepare-commit-msg]