repos:
  - repo: local
    hooks:
      - id: test
        name: test
        entry: sh -c 'echo $SHELL; echo $0; which sh; which bash; which zsh'
        language: system
        verbose: true
        stages: [prepare-commit-msg]
  - repo: https://github.com/FMsAkamineTaito/pre-commit-test
    rev: 98168ca0eefbf822ffef603398ff432c4a6ca76a
    hooks:
      - id: pr-status-check
        pass_filenames: false
        verbose: true
        stages: [prepare-commit-msg]
