repos:
  - repo: https://github.com/FMsAkamineTaito/pre-commit-test
    rev: 709ab6bcfd27f92d4d18c900a4d3c4f8e9fa7d45
    hooks:
      - id: pr-status-check
        name: pre-commit-test
        stages: [pre-merge-commit]
