repos:
  - repo: https://github.com/FMsAkamineTaito/pre-commit-test
    rev: 8a0ee404c46ebefaa4b1bc070e47717324b52a5b
    hooks:
      - id: pr-status-check
        name: pre-commit-test
        stages: [pre-commit, prepare-commit-msg]
        always_run: true
        verbose: true
        log_file: /Users/akaminetaito/Desktop/log.txt