repos:
  - repo: https://github.com/FMsAkamineTaito/pre-commit-test
    rev: 465130067147b90160641bed6be7e9e46862a6f7
    hooks:
      - id: pr-status-check
        name: pre-commit-test
        stages: [prepare-commit-msg]
        verbose: true
        log_file: /Users/akaminetaito/Desktop/log.txt
