repos:
  - repo: https://github.com/FMsAkamineTaito/pre-commit-test
    rev: 9f8a8e845b864643513bd0ed43ced6765288ec89
    hooks:
      - id: pr-status-check
        name: pre-commit-test
        stages: [pre-commit, prepare-commit-msg]
        always_run: true
        verbose: true
        log_file: /Users/akaminetaito/Desktop/log.txt