repos:
  - repo: local
    hooks:
      - id: test
        name: test
        entry: echo $SHELL && echo "######"
        language: system
        verbose: true
        stages: [prepare-commit-msg]
  - repo: https://github.com/FMsAkamineTaito/pre-commit-test
    rev: ecf1643ce3fb5cb40bbbe0c0e4e850c85728504e
    hooks:
      - id: pr-status-check
        pass_filenames: false
        verbose: true
        stages: [prepare-commit-msg]
