repos:
  - repo: https://github.com/FMsAkamineTaito/pre-commit-test
    rev: edfec1689262d93daf151a952a03f8ae6aec9add
    hooks:
      - id: pr-status-check
        name: pre-commit-test
        stages: [prepare-commit-msg]
