repos:
  - repo: https://github.com/FMsAkamineTaito/pre-commit-test
    rev: ee4d3ae8666478a8137e4012b16bb19d24cd21a6
    hooks:
      - id: pr-status-check
        name: pre-commit-test
        stages: [prepare-commit-msg]
        verbose: true
        log_file: /Users/akaminetaito/Desktop/log.txt
