repos:
  - repo: https://github.com/FMsAkamineTaito/pre-commit-test
    rev: 37dd809aec311880dcbf498981e2c6848fb6e7ae
    hooks:
      - id: pr-status-check
        name: pre-commit-test
        stages: [pre-commit]
        verbose: true
        log_file: /Users/akaminetaito/Desktop/log.txt