repos:
  - repo: https://github.com/FMsAkamineTaito/pre-commit-test
    rev: c61b0b3b94fe39f6d3a01079b9dc76f726a87177
    hooks:
      - id: pr-status-check
        name: pre-commit-test
        stages: [prepare-commit-msg]
        verbose: true
        log_file: /Users/akaminetaito/Desktop/log.txt
