repos:
  - repo: https://github.com/FMsAkamineTaito/pre-commit-test
    rev: 8a0ee404c46ebefaa4b1bc070e47717324b52a5b
    hooks:
      - id: pr-status-check
        name: pre-commit-test
        stages: [pre-commit, prepare-commit-msg]
        always_run: true
        verbose: true
        log_file: /Users/akaminetaito/Desktop/log.txt
  # - repo: local
  #   hooks:
  #     - id: handle-merge-failure
  #       name: handle-merge-failure
  #       entry: |
  #         bash -c '
  #           echo "handle-merge-failure"
  #           echo "handle-merge-failure" > "/Users/akaminetaito/Desktop/log.txt";
  #           echo $(ls .git/) > "/Users/akaminetaito/Desktop/log.txt";
  #           ls .git/
  #           sleep 5
  #         '
  #       language: system