repos:
  - repo: https://github.com/FMsAkamineTaito/pre-commit-test
    rev: 136d2be29f41965faa39f6aba3b601c4b46b2e8e
    hooks:
      - id: pr-status-check
        name: pre-commit-test
        stages: [pre-merge-commit]
        args:
          - "$(cat .git/MERGE_MSG)"
