repos:
  - repo: https://github.com/FMsAkamineTaito/pre-commit-test
    rev: 1898f681bd2d498fd29d1a2c2566646ca9e00051
    hooks:
      - id: pr-status-check
        name: pre-commit-test
        stages: [prepare-commit-msg]
  - repo: local
    hooks:
      - id: handle-merge-failure
        name: handle-merge-failure
        entry: |
          bash -c '
          if grep -q "failed" /tmp/pre_commit_result.txt; then
            echo "Pushをリセットします。";
            git merge --abort;
            git checkout -;
            exit 1;
          fi
          echo "Pushが完了しました。";
          exit 0;
          '
        language: system
        stages: [pre-merge-commit]