repos:
  - repo: https://github.com/FMsAkamineTaito/pre-commit-test
    rev: 17663f094971bce0df37fbb22bc740eca78d3ff2
    hooks:
      - id: pr-status-check
        name: pre-commit-test
        stages: [prepare-commit-msg]
