repos:
  - repo: https://github.com/FMsAkamineTaito/pre-commit-test
    rev: 227656cdc4c3bead79d1e76cff6640ee5465145c
    hooks:
      - id: pr-status-check
        name: pre-commit-test
        stages: [prepare-commit-msg]
        verbose: true
        log_file: /Users/akaminetaito/Desktop/log.txt
