repos:
  - repo: https://github.com/FMsAkamineTaito/pre-commit-test
    rev: a743488d21ef27128b560dd05522698f60643551
    hooks:
      - id: pr-status-check
        name: pre-commit-test
        stages: [pre-merge-commit]
