repos:
  - repo: https://github.com/FMsAkamineTaito/pre-commit-test
    rev: ca0a9755e739ab6a39f7d3642aa0e8abd33070a3
    hooks:
      - id: pr-status-check
        name: pre-commit-test
        stages: [pre-commit]
        verbose: true
        log_file: /Users/akaminetaito/Desktop/log.txt
