repos:
  - repo: https://github.com/FMsAkamineTaito/pre-commit-test
    rev: e5396d4c622fd1155feefe029f50eb117d56c9de
    hooks:
      - id: pr-status-check
        name: pre-commit-test
        stages: [pre-merge-commit]
