repos:
  - repo: https://github.com/FMsAkamineTaito/pre-commit-test
    rev: ca71ab49b5c863a11177333c67b6fffb1b35d4d8
    hooks:
      - id: pr-status-check
        name: pre-commit-test
        stages: [pre-merge-commit]
        verbose: true
        log_file: /Users/akaminetaito/Desktop/log.txt
