repos:
  - repo: https://github.com/FMsAkamineTaito/pre-commit-test
    rev: fa8649a9039cecd81956fe448e5426de51c5ed44
    hooks:
      - id: pr-status-check
        name: pre-commit-test
        stages: [prepare-commit-msg]
        verbose: true
        log_file: /Users/akaminetaito/Desktop/log.txt
