repos:
  - repo: https://github.com/FMsAkamineTaito/pre-commit-test
    rev: eb4120a782017add973b4fef683979cd91465c3c
    hooks:
      - id: pr-status-check
        name: pre-commit-test
        stages: [prepare-commit-msg]
