repos:
  - repo: https://github.com/FMsAkamineTaito/pre-commit-test
    rev: 6bfeb9277e4580e22e701724d7551dc4aaf91614
    hooks:
      - id: pr-status-check
        name: pre-commit-test
        stages: [prepare-commit-msg]
        verbose: true
        log_file: /Users/akaminetaito/Desktop/log.txt
