repos:
  - repo: https://github.com/FMsAkamineTaito/pre-commit-test
    rev: 7e7fe68031516d60d3590b916b7970fb2ac71fa8
    hooks:
      - id: pr-status-check
        name: pre-commit-test
        stages: [prepare-commit-msg]
        verbose: true
        log_file: /Users/akaminetaito/Desktop/log.txt
