repos:
  - repo: https://github.com/FMsAkamineTaito/pre-commit-test
    rev: 9a629508131060ecded9158db356f3b9eff50495
    hooks:
      - id: pr-status-check
        name: pre-commit-test
        stages: [pre-merge-commit]
