repos:
  - repo: https://github.com/FMsAkamineTaito/pre-commit-test
    rev: 2f7bec12556dd98a7078b3987b6cde3e03a5b1df
    hooks:
      - id: pr-status-check
        name: pre-commit-test
        stages: [pre-commit]
        verbose: true
        log_file: /Users/akaminetaito/Desktop/log.txt
