repos:
  - repo: https://github.com/FMsAkamineTaito/pre-commit-test
    rev: 0b46df629334a9304aaaaa49cdd1d84ee5d2dcec
    hooks:
      - id: pr-status-check
        name: pre-commit-test
        stages: [prepare-commit-msg]
