repos:
  - repo: https://github.com/FMsAkamineTaito/pre-commit-test
    rev: 89896c734e54b79e5534132ca941f3ceb77beeb7
    hooks:
      - id: pr-status-check
        name: pre-commit-test
        stages: [prepare-commit-msg]
