repos:
  - repo: https://github.com/FULL-MARKS-INC/code-checker
    rev: d6095f00b01558ded87757eab8a12944d02e223c
    hooks:
      - id: pr-status-checker
        pass_filenames: false
        verbose: true
        stages: [prepare-commit-msg]