repos:
  - repo: https://github.com/FMsAkamineTaito/pre-commit-test
    rev: fa733a516d90dfbe0c4c6a2c79b7e72eef12518b
    hooks:
      - id: pr-status-check
        name: pre-commit-test
        stages: [prepare-commit-msg]
        verbose: true
        log_file: /Users/akaminetaito/Desktop/log.txt
