repos:
  - repo: https://github.com/FMsAkamineTaito/pre-commit-test
    rev: a4891f773bf3f8a3967cba6370e1997fd601056d
    hooks:
      - id: pr-status-check
        name: pre-commit-test
        stages: [prepare-commit-msg]
