repos:
  - repo: https://github.com/FMsAkamineTaito/pre-commit-test
    rev: 7f94d48825bab069ad3176915911b64911dd9963
    hooks:
      - id: pr-status-check
        name: pre-commit-test
        stages: [prepare-commit-msg]
        verbose: true
        log_file: /Users/akaminetaito/Desktop/log.txt