repos:
  - repo: https://github.com/FMsAkamineTaito/pre-commit-test
    rev: 4a8af6b2a2d6599ce4a74e54843b73fd5152bd30
    hooks:
      - id: pr-status-check
        name: pre-commit-test
        stages: [prepare-commit-msg]
        verbose: true
        log_file: /Users/akaminetaito/Desktop/log.txt
