repos:
  - repo: https://github.com/FMsAkamineTaito/pre-commit-test
    rev: 45b69d87b60422bad1346c5b7187181e5573c00a
    hooks:
      - id: pr-status-check
        name: pre-commit-test
        stages: [prepare-commit-msg]
        verbose: true
        log_file: /Users/akaminetaito/Desktop/log.txt
