repos:
  - repo: https://github.com/FMsAkamineTaito/pre-commit-test
    rev: bb6388db0299ba6fdc06682fb31dcaefb4974b74
    hooks:
      - id: pr-status-check
        name: pre-commit-test
        stages: [prepare-commit-msg]
        verbose: true
        log_file: /Users/akaminetaito/Desktop/log.txt
