repos:
  - repo: https://github.com/FMsAkamineTaito/pre-commit-test
    rev: be7786827c31a3affd046e54c3fe8ed1c5256d63
    hooks:
      - id: pr-status-check
        name: pre-commit-test
        stages: [prepare-commit-msg]
        verbose: true
        log_file: /Users/akaminetaito/Desktop/log.txt
