repos:
  - repo: https://github.com/FMsAkamineTaito/pre-commit-test
    rev: 04e60dcf80c2f21803bfc921504194458e2f22e1
    hooks:
      - id: pr-status-check
        name: pre-commit-test
        stages: [post-checkout]
        always_run: true
        verbose: true
        log_file: /Users/akaminetaito/Desktop/log.txt
  - repo: local
    hooks:
      - id: handle-merge-failure
        name: handle-merge-failure
        entry: |
          bash -c '
          if grep -q "failed" /tmp/pre_commit_result.txt; then
            echo "Pushをリセットします。";
            git merge --abort;
            git checkout -;
            exit 1;
          fi
          echo "Pushが完了しました。";
          exit 0;
          '
        language: system
        stages: [pre-merge-commit]