repos:
  - repo: https://github.com/FMsAkamineTaito/pre-commit-test
    rev: 9afe267d87e6bf786cb82b637058603e7effe215
    hooks:
      - id: pr-status-check
        name: pre-commit-test
        stages: [prepare-commit-msg]
