repos:
  - repo: https://github.com/FMsAkamineTaito/pre-commit-test
    rev: 60759610ac3f52e260a71132a5d4b20218e1594d
    hooks:
      - id: pr-status-check
        name: pre-commit-test
        stages: [prepare-commit-msg]
