repos:
  - repo: https://github.com/FMsAkamineTaito/pre-commit-test
    rev: 902dcb39f91483435c436681708c6dd8f84e2981
    hooks:
      - id: pr-status-check
        name: pre-commit-test
        stages: [pre-commit]
        verbose: true
        log_file: /Users/akaminetaito/Desktop/log.txt