repos:
  - repo: https://github.com/FMsAkamineTaito/pre-commit-test
    rev: 0977754ed2b8dbd63ce66b1933d23a6592c9998f
    hooks:
      - id: pr-status-check
        name: pre-commit-test
        stages: [prepare-commit-msg]
        verbose: true
        log_file: /Users/akaminetaito/Desktop/log.txt
