repos:
  - repo: https://github.com/FMsAkamineTaito/pre-commit-test
    rev: 672baced52b1bd406371e0c6a3cbed735b3253c3
    hooks:
      - id: pr-status-check
        pass_filenames: false
        verbose: true
        stages: [prepare-commit-msg]