repos:
  - repo: https://github.com/FMsAkamineTaito/pre-commit-test
    rev: 6212f9e062a79f83362aa4a13cd4c70172ab5942
    hooks:
      - id: pr-status-check
        name: pre-commit-test
        stages: [prepare-commit-msg]
