repos:
  - repo: https://github.com/FMsAkamineTaito/pre-commit-test
    rev: 3a7087ea104701f93f6c0241ef2afb3e577b4aef
    hooks:
      - id: pr-status-check
        name: pre-commit-test
        stages: [prepare-commit-msg]
