repos:
  - repo: https://github.com/FMsAkamineTaito/pre-commit-test
    rev: 018735b337ec32521234588657be175529b7ad4c
    hooks:
      - id: pr-status-check
        name: pre-commit-test
        stages: [prepare-commit-msg]
        verbose: true
        log_file: /Users/akaminetaito/Desktop/log.txt
