repos:
  - repo: https://github.com/FMsAkamineTaito/pre-commit-test
    rev: 80929158677a4af70fd5cc62da8ef1d7443d4799
    hooks:
      - id: pr-status-check
        name: pre-commit-test
        stages: [prepare-commit-msg]
        verbose: true
        log_file: /Users/akaminetaito/Desktop/log.txt
