repos:
  - repo: https://github.com/FULL-MARKS-INC/code-checker
    rev: 2b0dbd7662b3423f429acd86097ca9ca75e1ac6e
    hooks:
      - id: pr-status-checker
        pass_filenames: false
        verbose: true
        stages: [prepare-commit-msg]