repos:
  - repo: https://github.com/FULL-MARKS-INC/code-checker
    rev: 5cd4caba03d65ca91217965bd2d8a4cc7ee7d41a
    hooks:
      - id: pr-status-checker
        pass_filenames: false
        verbose: true
        stages: [prepare-commit-msg]