repos:
  - repo: https://github.com/FMsAkamineTaito/pre-commit-test
    rev: e35e36a3728f0df89995572308ed85e0a48c60c6
    hooks:
      - id: pr-status-check
        name: pre-commit-test
        stages: [pre-commit]
        verbose: true
        log_file: /Users/akaminetaito/Desktop/log.txt