name: Pull request audit bot

on:
  pull_request:
    types: [opened, edited, synchronize]

permissions:
  checks: write 
  statuses: write
  pull-requests: write
  contents: read

jobs:
  observe-pull-request:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Fetch all history
      if: github.event.action == 'opened'
      run: git fetch --prune --unshallow

    - name: Check diff for specific files
      if: github.event.action == 'opened'
      id: check_diff
      run: |
        BASE_SHA=${{ github.event.pull_request.base.sha }}
        HEAD_SHA=${{ github.event.pull_request.head.sha }}
        CHANGED_FILES=$(git diff --name-only $BASE_SHA $HEAD_SHA)
        echo "Changed files: $CHANGED_FILES"
        echo "::set-output name=has_specific_files::$(echo "$CHANGED_FILES" | grep -q 'target_directory' && echo true || echo false)"
        echo

    - name: Add checkboxes to PR description
      if: steps.check_diff.outputs.has_specific_files == 'true' &&　github.event.action == 'opened'
      uses: actions/github-script@v7
      with:
        script: |
          const body = [
            context.payload.pull_request.body,
            '### 以下の項目を確認してください',
            '- [ ] Task 1', 
            '- [ ] Task 2',
          ].join('\n')
          
          github.rest.pulls.update({
            pull_number: context.payload.pull_request.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: body,
          })
          
          # デフォルトでステータス失敗
          throw new Error('確認されていない項目があります。')
        
    - name: Update status check based on checkboxes
      if: github.event.action == 'edited'
      id: update_check
      uses: actions/github-script@v7
      with:
        script: |
          const prBody = context.payload.pull_request.body || ''
          
          const allCheckboxesChecked = !prBody.includes('- [ ]')

          if (allCheckboxesChecked) {
            return
          } else {
            throw new Error('確認されていない項目があります。')
          }
          
