name: Pull request audit bot

on:
  pull_request:
    types: [opened, edited, synchronize]

permissions:
  checks: write 
  statuses: write
  pull-requests: write
  contents: read

jobs:
  observe-pull-request:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Fetch all history
      run: git fetch --prune --unshallow

    - name: Check diff for specific files
      id: check_diff
      run: |
        BASE_SHA=${{ github.event.pull_request.base.sha }}
        HEAD_SHA=${{ github.event.pull_request.head.sha }}
        CHANGED_FILES=$(git diff --name-only $BASE_SHA $HEAD_SHA)
        echo "Changed files: $CHANGED_FILES"
        echo "::set-output name=has_specific_files::$(echo "$CHANGED_FILES" | grep -q 'target_directory' && echo true || echo false)"
        echo

    - name: Add checkboxes to PR description
      if: steps.check_diff.outputs.has_specific_files == 'true' &&　github.event.action == 'opened'
      uses: actions/github-script@v7
      with:
        script: |
          const body = [
            context.payload.pull_request.body,
            '### 以下の項目を確認してください',
            '- [ ] Task 1', 
            '- [ ] Task 2',
          ].join('\n')

          github.rest.pulls.update({
            pull_number: context.payload.pull_request.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: body,
          })

    # - name: initialize PR status
    #   id: status
    #   uses: actions/github-script@v7
    #   with:
    #     script: |
    #       github.rest.checks.create({
    #         owner: context.repo.owner,
    #         repo: context.repo.repo,
    #         name: 'PR Checklist Status',
    #         head_sha: context.payload.pull_request.head.sha,
    #         status: 'completed',
    #         conclusion: 'failure',
    #         output: {
    #           title: '全ての項目を確認してください。',
    #           summary: 'PR本文にあるチェック項目を確認してください。'
    #         }
    #       })
          
    - name: Check PR description for completed checkboxes
      id: check_boxes
      uses: actions/github-script@v7
      with:
        script: |
          const prBody = context.payload.pull_request.body || ''
          const allCheckboxesChecked = !prBody.includes('- [ ]') && prBody.includes('- [x]')
          
          core.setOutput('all_checked', allCheckboxesChecked)

    - name: Update status check based on checkboxes
      uses: actions/github-script@v7
      with:
        script: |
          const allChecked = ${{ steps.check_boxes.outputs.all_checked }}

          const allChecked = true
          
          github.rest.checks.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            name: 'PR Checklist Status',
            head_sha: context.payload.pull_request.head.sha,
            status: 'completed',
            conclusion: allChecked ? 'success' : 'failure',
            output: {
              title: allChecked ? '完了' : '未完了',
              summary: allChecked ? '全ての項目が確認されました。' : '確認すべき項目が残っています。'
            }
          })
