name: Pull request audit bot

on:
  pull_request:
    types: [opened, edited, synchronize]

permissions:
  pull-requests: write
  contents: read

jobs:
  check-commiter:
    runs-on: ubuntu-latest
    outputs:
      should_continue: ${{ steps.check_is_fms.outputs.result }}
    steps:
    - name: Check all commiter are FMs member
      id: check_is_fms
      uses: actions/github-script@v7
      with:
        script: |
          const commitLists = await github.rest.pulls.listCommits({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number
          });
          
          const isAllCommitFromFms = commitLists["data"].every((commit) => {
              // マージコミットの場合はスキップ
              if (commit["parents"] && commit["parents"].length > 1) {
                return true;
              }
              
              const commitAuthor = commit["commit"]["author"]["name"]
              const commitAuthorEmail = commit["commit"]["author"]["email"]
          
              return commitAuthorEmail.includes("@fullmarks.co.jp") 
          })
          
          return isAllCommitFromFms
    
  pr_status_check:
    needs: check-commiter
    if: ${{ fromJSON(needs.check-commiter.outputs.should_continue) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
      - name: Get PR body
        id: pr_body
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const body = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number,
            });
            return body.data.body;
      - name: get_checklist_config
        id: get_checklist_config
        uses: mikefarah/yq@master
        with:
          cmd: |
            yq -o=json '.setting' setting/github_action_setting.yaml
      - name: Update PR body
        if: steps.get_checklist_config.outputs.result != '[]'
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const checklists = ${{ steps.get_checklist_config.outputs.result }};
            let result = "";
            let changedFiles = '${{ steps.changed-files.outputs.all_changed_files }}'.split(' ').filter(Boolean);

            console.log("changed files :", changedFiles)
            checklists.forEach(item => {
              const title = `## レビュワーは以下の項目を確認してください`;
              
              console.log("item :", item)
              let isTargetIncluded = false
              if(item.path.endsWith('/')){
                isTargetIncluded = changedFiles.some((path) =>{
                  return path.includes(item.path)
                })
              } else {
                isTargetIncluded = changedFiles.some((path) =>{
                  return path === item.path
                })
              }
              
              conosle.log("isTargetIncluded :", isTargetIncluded)
              if(isTargetIncluded){
                item.checklists.forEach(checklist => {
                  result += `${checklist}\n`;
                });
              }
            });

            if(!result){
              conosle.log("####")
              console.log("result is nothing")
              return
            }

            const originalBody = '${{ steps.pr_body.outputs.result }}';
            
            github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number,
              body: `${originalBody}\n${title}\n${result}`,
            });
            throw new Error('確認されていない項目があります。');

      - name: Update status check based on checkboxes
        if: github.event.action
        id: update_check
        uses: actions/github-script@v7
        with:
          script: |
            const prBody = context.payload.pull_request.body || ''
            
            const allCheckboxesChecked = !prBody.includes('- [ ]')
  
            if (allCheckboxesChecked) {
              return
            } else {
              throw new Error('確認されていない項目があります。')
            }
